# Site title and subtitle. This is used in _includes/header.html
title: 'JSTL is cool'

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/allanhortle/jstl-is-cool'

# Default categories (in order) to appear in the navigation
sections: [
    ['basic', 'The Basics'],
    ['core', 'Core'],
    ['fmt', 'Format'],
    ['fn', 'Function'],
    ['tag', 'Custom Tags'],
    ['hacks', 'Useful Hacks'],
    ['post', 'Posts']
]

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/jstl-is-cool'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
pygments: true

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the redcarpet Markdown renderer
markdown: redcarpet
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
